### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by stefanopagnin** [Daemonite/material#2] opened 2015-03-19 18:33 UTC
Hi, beatiful work! It's a wonderful themplate! Just one thing that is not perfect, the icons doesn't appear...do you have any solution for that? thanks

**Comment by sesemaya** [comment] 2015-03-22 23:28
Hi @stefanopagnin does the `console` report an error of finding the icon font files on the page?

**Comment by stefanopagnin** [comment] 2015-03-23 08:09
Hi @sesemaya, no error appear, but i found that the "base.min.css" missed this attributes: 
"
@font-face {
    font-family: iconfont;
	src: url('fonts/MaterialDesignIcon.eot');
	src: url('fonts/MaterialDesignIcon.eot?#i') format('embedded-opentype'),
	url('fonts/MaterialDesignIcon.woff') format('woff'),
	url('fonts/MaterialDesignIcon.ttf') format('truetype'),
	url('fonts/MaterialDesignIcon.svg#') format('svg');
    font-weight: normal;
    font-style: normal;
}
"
so the css files wasn't able to find the MaterialDesignIcon file. I tried with this, and all the icons was correct.

**Comment by modius** [comment] 2015-03-30 23:05
@stefanopagnin we can't reproduce the issue in the current HEAD of **master**.  Looks like you've found a fix for your environment so I'm going to close the issue.  If it rears up again, please let us know!

**Closed by modius** 2015-03-30 23:05 UTC

**Comment by stefanopagnin** [comment] 2015-03-31 07:49
@modius thanks for the support, i think that the REAL issues was the wrong path of the code in the font-face{..}, but yeah, i solved this little problem by myself, so thanks anyway! Beafitul work!

**Comment by sesemaya** [comment] 2015-03-31 22:25
@stefanopagnin the paths in the css files as well as any `href` or `src` in html templates are all based on the default setup which follows a very simple folder structure, if your project is set up in a different environment you should also change these paths accordingly. 

the easiest way to change the paths in css files is to modify the `$css-path` variable in `/sass/_variable.scss` file, and recompile sass to generate the new css files.

**Comment by stefanopagnin** [comment] 2015-04-01 11:44
@sesemaya many thanks, now it works great ! Thanks a lot for the support
